version: 0.2

phases:
    install:
        commands:
            - echo started...

    pre_build:
        commands:
            - echo building npm
            - npm install           

    build:
        commands:
            - echo deployment started..$BUILD_OUTPUT_BUCKET
            - aws cloudformation package --template-file ./hello-world/template.yml --output-template-file package.yml --s3-bucket $BUILD_OUTPUT_BUCKET
            
    post_build:
        commands:
            - echo deployment complete..
artifacts:
    files:
        - package.yml
