version: 0.2

phases:
    install:
        commands:
            - echo started...

    pre_build:
        commands:
            - npm install typescript -g
            - echo Stage 1
            - npm install  
            - echo building npm
            - echo Stage 2

    build:
        commands:
            - echo deployment started..$BUILD_OUTPUT_BUCKET
            - npm run cicd_deploy-dev
            - aws cloudformation package --template-file template.yml --output-template-file package.yml --s3-bucket $BUILD_OUTPUT_BUCKET
            
    post_build:
        commands:
            - echo deployment complete..
artifacts:
    files:
        - package.yml
