version: 0.2

phases:
    install:
        commands:
            - echo started...

    pre_build:
        commands:
            - npm install typescript -g
            - echo Stage 1
            - npm --prefix ./hello-world/ install  
            - echo building npm
            - echo Stage 2
            - npm run cicd_deploy-dev
            - find ./hello-world/node_modules -mtime +10950 -exec touch \;

    build:
        commands:
            - echo deployment started..$BUILD_OUTPUT_BUCKET
            - aws cloudformation package --template-file template.yml --output-template-file package.yml --s3-bucket $BUILD_OUTPUT_BUCKET
            
    post_build:
        commands:
            - echo deployment complete..
artifacts:
    files:
        - package.yml
