AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Function:
    Timeout: 5
    
Parameters:
  StageName:
    Type: String
    Default: dev
  ProductLine:
    Type: String
    Default: data-channel
  Region:
    Description: Region
    Type: String
    Default:  ap-south-1
    
Resources:
  hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: dist/handler.hello
      Runtime: nodejs10.x
      CodeUri: "./"
      Policies:
        - Version: '2012-10-17'
          Statement:
           - Effect: Allow
             Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:PutItem'
             Resource:
                'Fn::Join':
                   - ''
                   - - 'arn:aws:dynamodb:'
                     - Ref: 'AWS::Region'
                     - ':'
                     - Ref: 'AWS::AccountId'
                     
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get                     
          
      Events:
        CreateAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
        OtherOperationsAPI:
          Type: Api
          Properties:
            Path: /hello/{itemId}
            Method: ANY
  piifFileConfig:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pii
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
       - Key: Name
         Value: piifFileConfig
       - Key: EnvType
         Value: !Ref StageName
       - Key: EnvName
         Value: !Ref StageName
       - Key: ProductLine
         Value: !Ref ProductLine
       - Key: ProductComponent
         Value: NA
       - Key: Provisioner
         Value: aws-sam
       - Key: OwnerContact
         Value: NA
       - Key: MaintenanceContact
         Value: NA
       - Key: CodeRepo
         Value: https://github.com/urpalranjith/sam-test-basic.git
       - Key: PII
         Value: true

  reference:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: refer
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
       - Key: Name
         Value: reference
       - Key: EnvType
         Value: !Ref StageName
       - Key: EnvName
         Value: !Ref StageName
       - Key: ProductLine
         Value: !Ref ProductLine
       - Key: ProductComponent
         Value: NA
       - Key: Provisioner
         Value: aws-sam
       - Key: OwnerContact
         Value: NA
       - Key: MaintenanceContact
         Value: NA
       - Key: CodeRepo
         Value: https://github.com/urpalranjith/sam-test-basic.git
       - Key: PII
         Value: true